GadgetGrove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Your Project API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourproject.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('orders/', include('order.urls')),
    path('seller/', include('seller.urls')),
    path('account/', include('account.urls')),
    path('conversation/', include('conversation.urls')),
    path('authentication/', include('authentication.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from . import views

app_name='account'

urlpatterns = [
    path('history/', views.history, name='history'),
    path('<int:pk>/', views.order_details, name='order_details'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('comments/', views.account_comments, name='comments'),
    path('settings', views.settings, name='settings'),
    path('card/', views.card, name='card'),
    path('discounts/', views.discounts, name='discounts'),
    path('ads/', views.ads, name='ads'),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.details, name='details'),
    path('', views.items, name='items'),
    path('comments/<int:pk>/', views.comments, name='comments'),
    path('favorites/', views.favorites, name='favorites'),
    path('add_delete_favorites_compare/<int:pk>/', views.add_delete_favorites_compare, name='add_delete_favorites_compare'),
    path('compare/', views.compare, name='compare'),
    path('add_update_item/', views.add_update_item, name='add_update_item'),
    path('delete_item/<int:pk>/', views.delete_item, name='delete_item'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('<int:pk>/<int:amount>/', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/', views.delete_from_cart, name='delete_from_cart'),
    path('change/<int:pk>/', views.change_amount_items, name='change_amount_items'),
    path('order/<int:seller_id>/<int:total_price>/<int:total_amount>/', views.order, name='order'),
    path('order_review/<int:pk>/', views.order_review, name='order_review'),
    path('success/', views.success, name='success'),
    ]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('seller_catalog/<int:seller_id>/', views.seller_catalog, name='seller_catalog'),
    path('seller_reviews/<int:seller_id>/', views.seller_reviews, name='seller_reviews'),
    path('seller_contacts/<int:seller_id>/', views.seller_contacts, name='seller_contacts'),
    path('seller_schedule/<int:seller_id>/', views.seller_schedule, name='seller_schedule'),
    path('seller_about/<int:seller_id>/', views.seller_about, name='seller_about'),
]

core/models.py
from django.db import models

core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

core/views.py
from django.shortcuts import render

from item.models import Category, Item
from core.custom_functions import search_results


def frontpage(request):
    if request.user.is_authenticated:
        items = Item.objects.all().exclude(created_by=request.user)
    else:
        items = Item.objects.all()

    query = request.GET.get('query', '')
    categories = Category.objects.all()

    if query:
        return search_results(request, query)
            
    context = {'items': items,
                'categories': categories,
                }

    return render(request, 'core/frontpage.html', context)

core/templates/core/all_comments.html
{% load custom_filters %}

{% for comment in comments %}
    <div class="list-group-item">
        <div class="card-body bg-white mt-3 py-2 rounded">
            <div class="container-fluid">
                <div class="d-flex justify-content-between">
                    {% if your_comments %}
                        <h6>Comment about {{ comment.item.model }}</h6>
                    {% else %}
                        {% if comment.user.username %}
                            <h6>{{ comment.user.username }}</h6>
                        {% else %}
                            <h6>{{ comment.first_name }} {{ comment.last_name }}</h6>
                        {% endif %}
                    {% endif %}
                    {% if comment.rating %}
                        <div class="d-inline-flex gap-1">
                            {% for _ in comment.stars %}
                                <i class="fas fa-star" style="color: rgb(196, 111, 0);;"></i>
                            {% endfor %}
                            {% for _ in comment.hollow_stars %}
                                <i class="far fa-star" style="color: rgb(196, 111, 0);;"></i>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>   
                <small>{{ comment.comment_date }}</small>

                <p class="mt-2">{{ comment.comment }}</p>

                {% if comment.advantages %}
                    <p>Advantages: {{ comment.advantages }}</p>
                {% endif %}

                {% if comment.disadvantages %}
                    <P>Disadvantages: {{ comment.disadvantages }}</P>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

core/templates/core/all_items.html
{% load custom_filters %}

<div class="row">
    {% if items %}
        {% for item in items %}
            <div class="col-xl-2 col-md-4 col-lg-3 col-sm-6 mt-4">
                <div class="card-body bg-white py-3 px-2" style="margin: -10px; height: 330px;">
                    <div class="row">
                        <div class="col-md-10">
                            <a href="{% url 'item:details' item.id %} " style="text-decoration: none; color: inherit; ">
                                <div class="container" style="height: 140px; width: auto; align-items: center; display: flex;">
                                    {% if item.image_url and item.image_url.url %}
                                    <img src="{{ item.image_url.url }}" alt="Phone Image" alt="Phone Image" style="max-height: 140px; max-width: 100%; margin-left: 25px;">
                                    {% else %}
                                        <p>No image available</p>
                                    {% endif %}
                                </div>
                            </a>
                        </div> 
                        <div class="col-md-2">
                            <a href="{% url 'item:add_delete_favorites_compare' pk=item.id %}?model_option='favorites'" style="color: #ff9414"><p class="{% if request.user.is_authenticated %}{% if item|is_in_favorites:request.user %}fa{% else %}far{% endif %}{% else %}far{% endif %} fa-heart"></p></a>
                            <a href="{% url 'item:add_delete_favorites_compare' pk=item.id %}" style="{% if request.user.is_authenticated %}{% if item|is_in_compare:request.user %}color: #ff9414;{% else %}color: inherit;{% endif %}{% else %}color: inherit;{% endif %}"><p class="fas fa-balance-scale-right"></p></a>
                        </div>
                    </div> 

                    <a href="{% url 'item:details' item.id %} " style="text-decoration: none; color: inherit; ">
                        <small>Code: {{ item.id }}</small>
                        <h6 class="card-title">{{ item.model|format_string|safe }}</h6>
                        
                        {% if item.availability %}
                            <span style="color: green;">Available</span>
                        {% else %}
                            <span style="color: red;">Not available</span>
                        {% endif %}
                        
                        <p>{{ item.avg_rating }}</p>
                        
                        <div class="d-inline-flex gap-2">
                            {% render_item_stars item %}
                            <div class="container">
                                <a href="{% url 'item:comments' item.id %}" style="text-decoration: none; color: inherit">
                                    <div class="d-inline-flex gap-1">
                                        <i class="fas fa-comment" style="color: rgb(196, 111, 0);"></i> 
                                        {% if item.comments.count %} 
                                        <span style="margin-top: -5px;">{{ item.comments.count }}</span>
                                        {% endif %}   
                                    </div> 
                                </a>
                            </div>
                        </div>
                    </a>

                    <div class="d-flex justify-content-between mt-2">
                        <h6>{{ item.price }}$</h6>
                        {% if item.availability %}
                            <a href='{% url "order:add_to_cart" pk=item.id amount=1 %}' class="shadow-sm btn btn-outline-warning btn-sm" type="button">Add to cart</a>       
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        Nothing here
    {% endif %}
</div>

core/templates/core/all_items_2.html
{% load custom_filters %}

{% for item in items %}
    <div class="{% if order_id %}card{% else %}card-body py-1{% endif %} bg-white mt-1" style="min-width: 300px; margin-right: 10px;">
        <a href="{% if order_id %}{% url 'account:order_details' order_id %}{% else %}#{% endif %}" style="text-decoration: none; color: inherit;">
            <div class="row mt-3 mb-3">
                <div class="col-md-5">
                    <div class="text-center ">
                        {% if item.item.image_url and item.item.image_url.url %}
                        <img src="{{ item.item.image_url.url }}"  width="80">
                        {% else %}
                            <p>No image available</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-7">
                    <h6>{{ item.item.model|truncatechars:30 }}</h6>
                    {% if item.item.availability %}
                        <span style="color: green;">Available</span>
                    {% else %}
                        <span style="color: red;">Not available</span>
                    {% endif %}
                    <p>{{ item.amount }} items</p>
                    <h6>{{ item.item.price }} $/per item</h6>
                </div>
            </div>
        </a>
    </div>
{% endfor %}

core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}|GadgetGrove</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">   
  </head>
  <body style="background-color: rgb(243, 243, 243); overflow-x: hidden;">
  {% block navbar %}
    {% include 'core/navbar.html' %}
  {% endblock %}
  
  {% block navbar_main %}
    {% include 'core/navbar_main.html' %}
  {% endblock %}


  {% block conversation_navbar %}
    {% include 'conversation/conversations_navbar.html' %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
    {% include 'core/footer.html' %}
  {% endblock %}

  <style>
    .avatar-image{
      border-radius: 50%;
    }

    .chat-messages{
      height: 400px;
      overflow-y: auto;
    }

    .bg-light-warning {
    background-color: rgba(255, 241, 178, 0.649)
    }

    .bg-light-gray {
      background: rgba(228, 228, 228, 0.649);
    }

  </style>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
  </body>
</html>

core/templates/core/checking.html
<p>user_password: {{user_password}}</p>

core/templates/core/email_template.html
Hey {{name}}!

You are trying to registrate GadgetGrove account.

To verify your email address, please, use this link:

Hope you find some goods you like!

Kustov Ihor 

core/templates/core/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Footer Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>

  <footer class="footer mt-3">
  	 <div class="container">
  	 	<div class="row">
  	 		<div class="footer-col">
  	 			<h4>company</h4>
  	 			<ul>
  	 				<li><a href="#">about us</a></li>
  	 				<li><a href="#">our services</a></li>
  	 				<li><a href="#">privacy policy</a></li>
  	 				<li><a href="#">affiliate program</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>get help</h4>
  	 			<ul>
  	 				<li><a href="#">FAQ</a></li>
  	 				<li><a href="#">shipping</a></li>
  	 				<li><a href="#">returns</a></li>
  	 				<li><a href="#">order status</a></li>
  	 				<li><a href="#">payment options</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>online shop</h4>
  	 			<ul>
  	 				<li><a href="#">watch</a></li>
  	 				<li><a href="#">bag</a></li>
  	 				<li><a href="#">shoes</a></li>
  	 				<li><a href="#">dress</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>follow us</h4>
  	 			<div class="social-links">
  	 				<a href="#"><i class="fab fa-facebook-f"></i></a>
  	 				<a href="#"><i class="fab fa-twitter"></i></a>
  	 				<a href="#"><i class="fab fa-instagram"></i></a>
  	 				<a href="#"><i class="fab fa-linkedin-in"></i></a>
  	 			</div>
  	 		</div>
  	 	</div>
  	 </div>
  </footer>

</body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% load custom_filters %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="container-fluid mt-2">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>    
        </div>
    {% endfor %}
{% endif %}
<div class="d-flex">
    {% if path %}
        <a href="{% url 'frontpage' %}" class="mr-0 text-decoration-none">GadgetGrove/</a>
        <p class="mb-0">{{ path }}</p>
    {% endif %}
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 mt-3">
            <div class="card-body bg-white">
                <div class="container">
                    <div class="list-group list-group-flush">
                        {% for category in categories %} 
                            <a href="{% url 'item:items' %}? query={{ query }}&category={{ category.id }}&action=link" class="list-group-item list-group-item-action py-3 h6" href="#list-item-1">{{ category.name }}</a>
                        {% endfor %}
                    </div>  
                </div>
            </div>
            
        </div>
        <div class="col-md-10">
            {% render_items items request %}
        </div>
    </div>
</div>


{% endblock %}

core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg " style="background-color: rgba(255, 136, 0, 0.905);">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'frontpage' %}">GadgetGrove</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">          
        </ul>
        {% if request.user.is_authenticated %}
        <div>
            <a href="{% url 'logout' %}" class="btn btn-secondary" type="button">Logout</a>
        </div>
        {% else %}
        <div>
            <a href="{% url 'signup' %}" class="btn btn-success" type="button">Sign up</a>
            <a href="{% url 'login' %}" class="btn btn-secondary" type="button">Login</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>

core/templates/core/navbar_main.html
{% load custom_filters %}

<nav class="nav" id="mainNavbar" style="background-color: rgb(196, 111, 0);">
  <div class="container-fluid py-2">
    <div class="row">
      <div class="col-md-1" style="width: 170px;">
        <a class="navbar-brand" href="{% url 'frontpage' %}"><h4 style="margin-top: 5px;">Catalog</h4></a>
      </div>
      <div class="col-md-8 content-end">
        <form method="GET" class="mt-1" role="search" action="." style="display: flex;">
          <input name='query' value="{{ query }}" class="form-control me-2" type="search" placeholder="I'm looking for..." aria-label="Search">
          <button class="btn btn-warning" type="submit">Search</button>
        </form>
      </div>
      <div class="col-md-2 justify-content-end">
        <div class="d-inline-flex gap-3">
          <a href="{% url 'account:history' %}" style="text-decoration: none; color: inherit;">
            {% if profile_image %}
              <img src="{{ profile_image.url }}" style="width: 45px; height: 45px;" alt="User Avatar" class="avatar-image">
            {% else %}
              <button class="btn rounded" type="button" style="background-color: rgb(254,146,23 ); margin-top: 5px;">Account</button>
            {% endif %}        
          </a>
          <a href="{% url 'item:add_update_item' %}" class="fas fa-plus" style="text-decoration: none; color: inherit; font-size: 2rem; line-height: 1; margin-top: 7px; margin-left: 11px;"></a>
          <a href="{% url 'item:favorites' %}" class="far fa-heart" id="favorites_heart_link" style="text-decoration: none; color: inherit; font-size: 2rem; line-height: 1; margin-top: 7px; margin-left: 11px;"></a>
          <a href="{% url 'item:compare' %}" class="fas fa-balance-scale-right" style="text-decoration: none; color: inherit; font-size: 2rem; line-height: 1; margin-top: 7px; margin-left: 11px;"></a>
          <button class="navbar-toggler" type="submit" data-bs-toggle="offcanvas" id="navbar-toggler" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation"  style="border: none;">
            <span class="fas fa-shopping-cart fa-2x"></span>
          </button>      
        </div>
      </div>
    </div>  
  </div>
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header" style="background-color: rgba(255, 136, 0, 0.905);">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Cart</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" style="background-color: rgb(243, 243, 243)">
        {% if request.user.is_authenticated %}
          {% if sellers_data %}
            {% for seller_data in sellers_data.values %}
              <div class="card-body mb-3 bg-white rounded">
                <div class="list-group list-group-flush">
                  <div class="list-group-item">
                    <div class="container-fluid py-1">
                      <div class="row">
                        <a href="{% url 'seller:seller_catalog' seller_data.seller.id %}" class="close_offcanvas_link" style="text-decoration: none; color: inherit;">
                            {% if seller_data.seller.personal_information_user.get.avatar_url %}
                            <div class="col-md-2">
                                <div class="container d-flex align-items-center" style="width: 50px; height: 50px;">
                                    <img src="{{ seller_data.seller.personal_information_user.get.avatar_url.url }}" style="width: 40px; height: 40px;" alt="User Avatar" class="avatar-image">
                                </div>
                            </div>
                            <div class="col-md-9">
                            {% else %}
                            <div class="col-md-12">
                            {% endif %}
                              <div class="contaniner" style="margin-top: 10px;">
                                <h6>{{ seller_data.seller.username }}</h6>
                              </div>
                            </div>
                          </div>
                        </a>
                    </div>
                  </div>
                  <div class="list-group-item">
                    <div class="container-fluid">
                      <div class="list-group list-group-flush">
                        {% for cart_item in seller_data.items %}
                        <div class="list-group-item">
                          <div class="py-2">
                              <div class="d-flex">
                                <div class="card-body" style="width: 100px;">
                                  {% if cart_item.item.image_url and cart_item.item.image_url.url %}
                                  <img src="{{ cart_item.item.image_url.url }}" style="max-width: 80px; max-height: 100%; margin-left: -30px;">
                                  {% else %}
                                      <p>No image available</p>
                                  {% endif %}  
                                </div>
                                <div class="card-body" style="width: 350px; height: 140px;">
                                  <div class="d-flex justify-content-between align-items-center">
                                    <h7>{{ cart_item.item.model|format_string|safe }}</h7>
                                    <a href="{% url 'order:delete_from_cart' pk=cart_item.id %}" class="btn btn-danger" type="submit" style="margin-right: -20px;">del</a>
                                  </div>
                                  <h7>{% if cart_item.item.availability %}Available{% else %}Not available{% endif %}</h7>
                                  <p>{{ cart_item.item.price }} $/ per item </p>
                                  <div class="d-flex justify-content-between">
                                    <form method="POST" action="{% url 'order:change_amount_items' pk=cart_item.id %}">
                                      {% csrf_token %}
                                      <button class="value-button" id="decrease" name="action" value="decrease" type="submit">-</button>
                                      <input type="number" value="{{ cart_item.amount }}" class="input_field">
                                      <button class="value-button" id="increase" name="action" value="increase" type="submit">+</button>
                                    </form>                            
                                    <h4>{{ cart_item.total_item_price }} $</h4>
                                  </div>
                                </div>
                                
                              </div>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                  <div class="list-group-item">
                    <div class="container-fluid py-1">
                      <div class="d-flex justify-content-between">
                        <h7>Total price will be:</h7>
                        <h4>{{ seller_data.total_price }} $</h4>
                      </div>
                      <div class="row">
                        <a href="{% url 'order:order' seller_id=seller_data.seller.id total_price=seller_data.total_price total_amount=seller_data.total_amount %}" class="close_offcanvas_link btn btn-warning" type="button">Purchase</a>
                        <a href="{% url 'seller:seller_catalog' seller_data.seller.id %}" class="close_offcanvas_link btn btn-outline-warning mt-1" type="button">Other author suggestions</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <h3>It seems you haven't added any items in your cart yet. Take your first.</h3>
          {% endif %}
        {% else %}
          <h3>You need to be authenticated in order to make a purchase.</h3>
        {% endif %}
    </div>
  </div>
</nav>

<style>
  .fixed-navbar {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1000;
    background-color: rgb(196, 111, 0);
  }

  .value-button {
    display: inline-block;
    border: 1px solid #ddd;
    margin-bottom: 5px;
    width: 30px;
    height: 30px;
    text-align: center;
    vertical-align: middle;
    line-height: 30px;
    background: #eee;
  }

  form #decrease {
    margin-right: -4px;
    border-radius: 8px 0 0 8px;
  }

  form #increase {
    margin-left: -4px;
    border-radius: 0 8px 8px 0;
  }

  .value-button:hover {
    cursor: pointer;
  }


  .input_field {
    text-align: center;
    border: none;
    border-top: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
    width: 30px;
    height: 30px;
  }

  input[type=number]::-webkit-inner-spin-button,
  input[type=number]::-webkit-outer-spin-button {
      -webkit-appearance: none;
      margin: 0;
  }
</style>


<script>
  document.getElementById('favorites_heart_link').addEventListener('click', function () {
    localStorage.removeItem('is_available');
  });

  document.addEventListener('scroll', function() {
      scrollPosition = window.scrollY
      if (scrollPosition > 56) {
        const navbar = document.getElementById('mainNavbar')
        navbar.classList.add('fixed-navbar');
      } else {
        const navbar = document.getElementById('mainNavbar')
        navbar.classList.remove('fixed-navbar');
      }
  });

  window.addEventListener('DOMContentLoaded', function() {
    const navbar_state = localStorage.getItem('is_open') === 'true';
    const navbar = document.getElementById('offcanvasNavbar');
    if (navbar_state) {
      const navbar = document.getElementById('offcanvasNavbar');
      navbar.classList.add('show');
    }
  });

  document.getElementById('offcanvasNavbar').addEventListener('show.bs.offcanvas', function () {
    localStorage.setItem('is_open', 'true');
  });

  document.getElementById('offcanvasNavbar').addEventListener('hidden.bs.offcanvas', function () {
    localStorage.setItem('is_open', 'false');
  });

  document.addEventListener('click', function (event) {
    if (event.target.classList.contains('close_offcanvas_link')) {
      localStorage.removeItem('is_open');
    }
  });


  
</script>