GadgetGrove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Your Project API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourproject.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('orders/', include('order.urls')),
    path('seller/', include('seller.urls')),
    path('account/', include('account.urls')),
    path('conversation/', include('conversation.urls')),
    path('authentication/', include('authentication.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('conversations/', views.conversations, name='conversations'),
    path('conversations/<str:item_id>/', views.conversation, name='conversation'),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
]

conversation/models.py
from django.db import models
from django.utils import timezone

from item.models import Item
from authentication.models import User as CustomUser


def current_time():
    return timezone.now().time()


class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(CustomUser, related_name='conversation_members')
    created_by = models.ForeignKey(CustomUser, related_name='conversation_creator', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)
        
    def __str__(self):
        return ", ".join([member.username for member in self.members.all()])


class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    created_by = models.ForeignKey(CustomUser, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.created_by} {self.created_at}'

conversation/views.py
from django.shortcuts import render, redirect
from .models import Conversation, ConversationMessage
from item.models import Item
from core.custom_functions import search_results



def conversations(request):
    if request.user.is_authenticated:
        option = 'conversations'
        query = request.GET.get('query', '')
        if query:
            return search_results(request, query)
        have_messages = False
        conversations = Conversation.objects.filter(members=request.user)
        if conversations:
            for conversation in conversations:
                if conversation.messages.all():
                    have_messages = True
                    break
        my_ads = request.GET.get('my_ads', '1')
        if conversations:
            if my_ads == '1':
                conversations = conversations.exclude(created_by=request.user)
            else:
                conversations = conversations.filter(created_by=request.user)

        context = {'option': option, 
                   'my_ads': my_ads,
                   'conversations': conversations,
                   'have_messages': have_messages
                   }

        return render(request, 'conversation/conversations.html', context)
    else:
        return redirect('login')


def conversation(request, item_id):
    if request.user.is_authenticated:
        item = Item.objects.get(id=item_id)
        query = request.GET.get('query', '')
        if query:
            return search_results(request, query)
        try:
            conversation = Conversation.objects.get(item=item, members=request.user)
        
        except:
            conversation = Conversation()
            conversation.item = item
            conversation.created_by = request.user
            conversation.save()

            conversation.members.add(request.user)
            conversation.members.add(item.created_by)
            conversation.save()

        try:
            messages = ConversationMessage.objects.filter(conversation=conversation)
            if len(messages) < 100:
                messages = messages[:100]
            else:
                messages = messages[len(messages)-100:]
        except:
            messages = ''
        
        context = {'conversation': conversation,
                   'messages': messages,
                   }
        
        return render(request, 'conversation/conversation.html', context)
    else:
        return redirect('login')

conversation/templates/conversation/conversation.html
{% extends 'account/account_base.html' %}

{% load custom_filters %}

{% block extra_content %}
<div class="card-body bg-white rounded">
    <div class="list-group list-group-flush">
        <div class="list-group-item">
            <div class="row">
                <div class="col-md-2">
                    <div class="container d-flex align-items-center" style="width: 80px; height: 80px;">
                        {% if conversation.created_by.personal_information_user.avatar_url %}
                            <img {% if request.user != conversation.created_by %}src="{{ conversation.created_by.personal_information_user.get.avatar_url.url }}"{% else %}src="{{ conversation.item.created_by.personal_information_user.get.avatar_url.url }}"{% endif %} style="width: 70px; height: 70px;" alt="User Avatar" class="avatar-image">
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="contaniner" style="margin-top: 30px;">
                        {% if request.user != conversation.created_by %}
                        <h6>{{ conversation.created_by.username }}</h6>
                        {% else %}
                            <h6>{{ conversation.item.created_by.username }}</h6>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="list-group-item">
            <div class="row">
                <div class="col-md-2">
                    <div class="container" style="width: 80px; height: 80px; align-items: center;">
                        {% if conversation.item.image_url.url %}
                            <img src="{{ conversation.item.image_url.url }}" style="width: 70px; height: 70px;">
                        {% else %}
                            <p>No image available</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="container-fluid" style="margin-top: -15px; margin-left: -11px;">
                        <div class="d-inline-flex gap-3 py-2">
                            <p>{% if conversation.item.availability %}Available{% else %}Not available{% endif %}</p>
                            <p>{{ conversation.item.model|truncatechars:50 }} </p>    
                        </div>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6>{{ conversation.item.price }} $</h6>
                        <p>Code: {{ conversation.item.id }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="list-group-item">
            <div class="lg:w-2/4 lg:mx-auto py-4 bg-white rounded">
                <div class="chat-messages space-y-3" id="chat-messages">
                    {% for message in messages %}
                        {% if message.created_by == request.user %}
                        <div class="px-3 py-1 mt-2 bg-light-warning rounded" style="width: 350px; margin-left: auto;">
                        {% else %}
                        <div class="px-3 py-1 mt-2 bg-light-gray rounded" style="width: 350px; margin-right: auto;">
                        {% endif  %}
                        <div class="d-flex justify-content-between">
                            <p>{{ message.created_by.username }}</p>
                            <p>{{ message.created_at }}</p>
                        </div>
                        <p>{{ message.content }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
            <form method="POST" action="." style="display: flex;">
                {% csrf_token %}
                <input class="form-control" type="text" name="content" placeholder="Your message..." id="chat-message-input" style="margin-right: 5px;">
                <button class="btn btn-warning" id="chat-message-submit">Submit{{ messages.count }}</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{{ conversation.id|json_script:"json-conversationid" }}
{{ request.user.username|json_script:"json-username" }}


<script>
    const conversationId = JSON.parse(document.getElementById('json-conversationid').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + conversationId
        + '/'
    );

    chatSocket.onmessage = function(e) {
        console.log('onmessage')

        const data = JSON.parse(e.data);

        if (data.message) {
            let html = '<div class="px-3 py-1 mt-2';

            if (data.username === userName) {
                html += ' bg-light-warning';
            } else {
                html += ' bg-light-gray';
            }

            html += ' rounded"';

            if (data.username === userName) {
                html += ' style="width: 350px; margin-left: auto;">';
            } else {
                html += ' style="width: 350px; margin-right: auto;">';
            }
            html += '<div class="d-flex justify-content-between">';
            html += '<p>' + data.username + '</p>';
            html += '<p>' + data.created_at + '</p></div>';
            html += '<p>' + data.message + '</p></div>';

            document.querySelector('#chat-messages').innerHTML += html;

            scrollToBottom();
        } else {
            alert('The message was empty!');
        }
    }

    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault();

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'conversation_id': conversationId
        }))

        messageInputDom.value = '';

        return false;
    }

    function scrollToBottom() {
        const objDiv = document.querySelector('#chat-messages');
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    scrollToBottom();
</script>
{% endblock %}

conversation/templates/conversation/conversation_template.html
<div class="card-body bg-white rounded mt-1 py-3">
    <div class="container-fluid">
        <a href="{% url 'conversation:conversation' conversation.item.id %}" style="text-decoration: none; color: inherit;">
            <div class="row">
                {% if conversation.created_by.personal_information_user.avatar_url %}
                    <div class="col-md-2">
                        <div class="container" style="width: 80px; height: 80px; align-items: center;">
                            <img {% if request.user != conversation.created_by %}src="{{ conversation.created_by.personal_information_user.get.avatar_url.url }}"{% else %}src="{{ conversation.item.created_by.personal_information_user.get.avatar_url.url }}"{% endif %} style="width: 70px; height: 70px;" alt="User Avatar" class="avatar-image">
                        </div>
                    </div>
                <div class="col-md-9">
                {% else %}
                <div class="col-md-12">
                {% endif %}
                    <div class="d-flex justify-content-between">
                        {% if request.user != conversation.created_by %}
                            <h6>{{ conversation.created_by.username }}</h6>
                        {% else %}
                            <h6>{{ conversation.item.created_by.username }}</h6>
                        {% endif %}
                        <p>{{ conversation.modified_at }}</p>    
                    </div>
                    <div class="container-fluid" style="margin-top: -15px; margin-left: -11px;">
                        <div class="d-inline-flex gap-3">
                            <p>{% if conversation.item.availability %}Available{% else %}Not available{% endif %}</p>
                            <p>{{ conversation.item.model|truncatechars:50 }} </p>    
                        </div>
                    </div>
                    <div class="d-inline-flex gap-1">
                        {% if conversation.messages.last.created_by == request.user %}
                            <p>You: </p>
                        {% else %}
                            <p>{{ conversation.messages.last.created_by }}: </p>
                        {% endif %}
                        <p>{{ conversation.messages.last.content|truncatechars:80 }}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>

conversation/templates/conversation/conversations.html
{% extends 'account/account_base.html' %}

{% load custom_filters %}

{% block extra_content %}
    <div class="card-body bg-white rounded py-2">
        <div class="container">
            <div class="list-group list-group-flush">
                <div class="list-group-item">
                    <h4>Conversations</h4>
                </div>
                <div class="list-group-item">
                    <div class="d-inline-flex gap-3">
                        <a href="{% url 'conversation:conversations' %}?my_ads=1" {% if my_ads == '1' %}class="btn btn-warning px-5"{% else %}class="btn btn-outline-warning px-5"{% endif %} type="button">I sell</a>
                        <a href="{% url 'conversation:conversations' %}?my_ads=0" {% if my_ads == '0' %}class="btn btn-warning px-5"{% else %}class="btn btn-outline-warning px-5"{% endif %} type="button">I buy</a>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    {% if have_messages %}
        {% for conversation in conversations %}
            {% if conversation.messages.all %}
                {% render_conversation conversation request %}
            {% endif %}
        {% endfor %}
    {% else %}
    <div class="card-body bg-white rounded mt-1 py-3">
        <div class="container-fluid">
            <div class="text-center">
                <h4>You do not have any conversations. Send someone a message.</h4>
                <a href="{% url 'frontpage' %}" class="btn btn-warning" type="button">Go shopping</a>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

conversation/templates/conversation/conversations_navbar.html
{% load custom_filters %}

<div style="position: fixed; bottom: 20px; right: 20px; z-index: 1000;">
    <button class="btn btn-warning" type="button" data-bs-toggle="offcanvas" data-bs-target="#conversationsNavbar" aria-controls="conversationsNavbar" aria-label="Toggle navigation">Chats</button>
</div>
<div class="offcanvas offcanvas-end" tabindex="-1" id="conversationsNavbar" aria-labelledby="conversationsNavbarLabel">
    <div class="offcanvas-header" style="background-color: rgba(255, 136, 0, 0.905);">
        <h5 class="offcanvas-title" id="conversationsNavbarLabel">All chats</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" style="background-color: rgb(243, 243, 243);">
        {% if conversations %}
            {% if conversations == '0' %}
                <h4>To start communicating, please register.</h4>
            {% else %}
                <div class="list-group list-group-flush">
                    {% for conversation in conversations %}
                        {% if conversation.messages.all %}
                            {% render_conversation conversation request %}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        {% else %}
            <div class="container">
                <h4>You do not have any conversations. Send someone a message.</h4>
            </div>
        {% endif %}
    </div>
</div>