GadgetGrove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Your Project API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourproject.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('orders/', include('order.urls')),
    path('seller/', include('seller.urls')),
    path('account/', include('account.urls')),
    path('conversation/', include('conversation.urls')),
    path('authentication/', include('authentication.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from . import views

app_name='account'

urlpatterns = [
    path('history/', views.history, name='history'),
    path('<int:pk>/', views.order_details, name='order_details'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('comments/', views.account_comments, name='comments'),
    path('settings', views.settings, name='settings'),
    path('card/', views.card, name='card'),
    path('discounts/', views.discounts, name='discounts'),
    path('ads/', views.ads, name='ads'),
]

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('conversations/', views.conversations, name='conversations'),
    path('conversations/<str:item_id>/', views.conversation, name='conversation'),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.details, name='details'),
    path('', views.items, name='items'),
    path('comments/<int:pk>/', views.comments, name='comments'),
    path('favorites/', views.favorites, name='favorites'),
    path('add_delete_favorites_compare/<int:pk>/', views.add_delete_favorites_compare, name='add_delete_favorites_compare'),
    path('compare/', views.compare, name='compare'),
    path('add_update_item/', views.add_update_item, name='add_update_item'),
    path('delete_item/<int:pk>/', views.delete_item, name='delete_item'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('<int:pk>/<int:amount>/', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/', views.delete_from_cart, name='delete_from_cart'),
    path('change/<int:pk>/', views.change_amount_items, name='change_amount_items'),
    path('order/<int:seller_id>/<int:total_price>/<int:total_amount>/', views.order, name='order'),
    path('order_review/<int:pk>/', views.order_review, name='order_review'),
    path('success/', views.success, name='success'),
    ]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('seller_catalog/<int:seller_id>/', views.seller_catalog, name='seller_catalog'),
    path('seller_reviews/<int:seller_id>/', views.seller_reviews, name='seller_reviews'),
    path('seller_contacts/<int:seller_id>/', views.seller_contacts, name='seller_contacts'),
    path('seller_schedule/<int:seller_id>/', views.seller_schedule, name='seller_schedule'),
    path('seller_about/<int:seller_id>/', views.seller_about, name='seller_about'),
]

item/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from authentication.models import User as CustomUser

class TimeStampTZField(models.DateTimeField):
    def db_type(self, connection):
        return 'TIMESTAMPTZ'


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class CategoryBrand(models.Model):
    category = models.ForeignKey(Category, related_name='category_brands', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='category_brands', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('category', 'brand')

    def __str__(self):
        return f'{self.category} {self.brand}'
    

class Item(models.Model):
    created_by = models.ForeignKey(CustomUser, related_name='items', on_delete=models.CASCADE)
    category_brand = models.ForeignKey(CategoryBrand, related_name='items', on_delete=models.CASCADE)
    model = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    availability = models.BooleanField(default=True)
    image_url = models.ImageField(upload_to='item_images', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('model',)

    def __str__(self):
        return self.model
    

class Comments(models.Model):
    item = models.ForeignKey(Item, related_name='comments', on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=100)
    comment = models.TextField()
    advantages = models.CharField(max_length=255, null=True, blank=True)
    disadvantages = models.CharField(max_length=255, null=True, blank=True)
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Comments'
        ordering = ('-comment_date', )
    
    def __str__(self):
        return f'{self.first_name} for {self.item.model}'
    

class FavoriteCompare(models.Model):
    user = models.ForeignKey(CustomUser, related_name='favorite_compares', on_delete=models.CASCADE)
    favorite_items = models.ManyToManyField(Item, related_name='favorites')
    compare_items = models.ManyToManyField(Item, related_name='compares')

    def __str__(self):
        return self.user.username

item/forms.py
from item.models import Comments, Item
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('first_name', 'last_name', 'email', 'comment', 'advantages', 'disadvantages')
        
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First name'}), 
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last name'}), 
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), 
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Tell us about your purchase'}),
            'advantages': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Advantages'}), 
            'disadvantages': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Disadvantages'}),
        }


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('availability', 'image_url')

        widgets = {
            'image_url': forms.ClearableFileInput(),
        }

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .models import CategoryBrand, Category, Brand, FavoriteCompare, Comments, Item
from .forms import CommentForm
from core.custom_functions import get_seller_info, search_results


def add_update_item(request):
    if request.user.is_authenticated:
        query = request.GET.get('query', '')
        if query:
            return search_results(request, query)
         
        item_id = request.GET.get('item_id', '')
        if request.method == 'POST':
            item_id = request.POST.get('item_id', '')
            
            item = get_object_or_404(Item, id=int(item_id)) if item_id else Item()
            fields = {
                'model': request.POST.get('new_title_input'),
                'price': request.POST.get('new_price_input')
            }
            for field, value in fields.items():
                if not value:
                    messages.error(request, f'The {field} field must be filled in!')
                    return redirect(request.META.get('HTTP_REFERER', 'frontpage'))
            
            try:
                float(fields["price"])
            except:
                messages.error(request, f'The price field must be integer or float number!')
                return redirect(request.META.get('HTTP_REFERER', 'frontpage'))
            
            selected_category = request.POST.get('category-select-item')
            selected_brand = request.POST.get('brand-select')
            if selected_category=='-1' or selected_brand=='-1' or not selected_category or not selected_brand:
                messages.error(request, 'Category and brand should be selected.')
                return redirect(request.META.get('HTTP_REFERER', 'frontpage'))
            
            category_brand = CategoryBrand.objects.get(category=int(selected_category), brand=int(selected_brand))

            availability = request.POST.get('is_available', False) == 'on'
            image_url = request.FILES.get('new_image')
            
            if not image_url:
                if item_id:
                    image_url = item.image_url

            item.created_by = request.user
            item.category_brand = category_brand
            item.model = fields['model']
            item.description = request.POST.get('new_description_input')
            item.price = fields['price']
            item.image_url = image_url
            item.availability = availability

            item.save()

            if item_id:
                messages.success(request, 'Your ad was updated successfully')
                return redirect(request.META.get('HTTP_REFERER', 'frontpage'))

            messages.success(request, 'Your ad was added successfully')
            return redirect('frontpage')
        else:
            selected_brand = ''
            item = ''
            all_categories = Category.objects.all()
            selected_category = request.GET.get('category', '-1')

            brands = Brand.objects.all()

            if item_id:
                item = Item.objects.get(id=item_id)
                if selected_category == '-1':
                    selected_category = str(item.category_brand.category.id)
                selected_brand = item.category_brand.brand.id

            if selected_category:
                if selected_category != '-1':
                    brands = Brand.objects.filter(category_brands__category_id=int(selected_category))                
                    
            context = {'all_categories': all_categories,
                       'brands': brands,
                       'selected_category': int(selected_category),
                       'selected_brand': selected_brand,
                       'item': item,
                       'item_id': item_id
                       }

            return render(request, 'item/add_update_item.html', context)
    
    return redirect('login')


def delete_item(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, pk=pk)
        item.delete()

        messages.success(request, 'The item was removed successfully')
        return redirect('account:ads')
    else:
        return redirect('login')


def delete_items(request):
    selected_items = request.GET.get('selectedValues')
    selected_items = selected_items.split(',')
    if selected_items:
        for value in selected_items:
            if value:
                item = get_object_or_404(Item, pk=int(value))
                item.delete()
            else:
                messages.success(request, 'No item selected')
                return redirect('account:ads')
        messages.success(request, 'The items was removed successfully')
        return redirect('account:ads')


def details(request, pk):
    item = Item.objects.get(id=pk)
    related_items = Item.objects.filter(category_brand__category=item.category_brand.category).exclude(id=pk)[0:6]
    query = request.GET.get('query', '')
    comments = Comments.objects.filter(item_id=pk)
    info = get_seller_info(item.created_by.id)
    seller_info = info[0]
    seller_additional_info = info[1]
    amount_orders = info[2]
    
    if query:
        return search_results(request, query)

    context = {'item': item,
                'related_items': related_items,
                'comments': comments,
                'seller_info': seller_info,
                'seller_additional_info': seller_additional_info,
                'amount_orders': amount_orders,
                }
    return render(request, 'item/details.html', context)


def items(request):
    query = request.GET.get('query', '')
    if query:
        return search_results(request, query)

    path = ''
    category = ''
    brands = ''

    category_id = request.GET.get('category', 0)

    if category_id:
        if request.user.is_authenticated:
            items = Item.objects.filter(category_brand__category=category_id).exclude(created_by=request.user)
        else:
            items = Item.objects.filter(category_brand__category=category_id)
        category = Category.objects.get(id=category_id)

    brand_id = request.GET.get('brand')
    if brand_id:
        items = items.filter(category_brand__brand = brand_id)

    if request.method == 'GET':
        action = request.GET.get('action')
        if action == 'form':
            selected_brands = request.GET.getlist('selected_brands')
            items = items.filter(category_brand__brand__in=selected_brands)

    brands = Brand.objects.filter(category_brands__category=category_id)

    path_brands = list(brands)

    if len(path_brands) > 3:
        path_brands = path_brands[:3]

    for brand in path_brands:
        path += f'{brand.name}, '
    
    path = path[:-2] + '...'
    
    context = {'items': items,
                'brands': brands,
                'path': path,
                'category_id': int(category_id),
                'category': category,
                'path': path,
                }

    return render(request, 'item/items.html', context)


def comments(request, pk):
    query = request.GET.get('query', '')
    if query:
        return search_results(request, query)
    
    comments = Comments.objects.filter(item_id=pk)
    item = Item.objects.get(id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            messages.success(request, 'Your comment was saved successfully')
            comment = form.save(commit=False)
            comment.item_id = pk
            selected_rate = request.POST.getlist('inlineRadioOptions')
            if selected_rate:
                comment.rating = int(selected_rate[0])
            comment.save()

            return redirect(request.META.get('HTTP_REFERER', 'frontpage'))

        messages.error(request, 'Something wrong with your comment, please enter correct information')


    else:
        if request.user.is_authenticated:
            initial = {
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
            }
            form = CommentForm(initial=initial)
        else:
            form = CommentForm()

    context = {'form': form,
                'comments': comments,
                'item': item,
                }

    return render(request, 'item/comments.html', context)


def favorites(request):
    if request.user.is_authenticated:
        option = 'favorites'
        query = request.GET.get('query', '')
        if query:
            return search_results(request, query)
        
        user_items = FavoriteCompare.objects.get_or_create(user=request.user)[0]
        items = user_items.favorite_items.all()
        all_categories = set(item.category_brand.category for item in items)
        all_sellers = set(item.created_by for item in items)
        selected_category = request.GET.get('category', '-1')
        selected_seller = request.GET.get('seller', '-1')
        is_available = request.GET.get('is_available', '')
        input = request.GET.get('input', '')
        
        if input:
            items = items.filter(model__icontains=input)
                
        if selected_category != '-1':
            items = items.filter(category_brand__category = selected_category)
            
        if selected_seller != '-1':
            items = items.filter(created_by__username = selected_seller)

        if is_available == "true":
            items = items.filter(availability = True)

        context = {'option': option,
                   'items': items,
                   'all_categories': all_categories,
                   'selected_category': int(selected_category),
                   'selected_seller': selected_seller,
                   'all_sellers': all_sellers,
                   'is_available': is_available,
                   }

item/templates/item/compare.html
{% extends 'core/base.html' %}

{% load custom_filters %}

{% block content %}
<div class="container-fluid">
    <h3>Item comparison</h3>
    {% if items %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 px-0">
                <div class="card-body bg-white">
                    <div class="list-group list-group-flush">
                        <div class="list-group-item" style="height: 283px;">
                            <h5>Show category:</h5>
                            {% if categories %}
                                {% for category in categories %}
                                    <a href="{% url 'item:compare' %}?selected_category={{ category.id }}" style="color: inherit;">{% if category.id == selected_category %}<strong>{{ category.name }}</strong>{% else %}{{ category.name }}{% endif %}</a>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="list-group-item">
                            <h6>Description</h6>
                        </div>
                    </div>          
                </div>
            </div>
            <div class="col-md-10 px-0">
                <div class="gallery-container overflow-auto">
                    <div class="d-flex">
                        {% for item in items %}
                            <div class="list-group list-group-flush">
                                <div class="card-body bg-white" style="width: 250px;">
                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-md-10">
                                                <a href="{% url 'item:details' item.id %} " style="text-decoration: none; color: inherit; ">
                                                    <div class="text-center">
                                                        {% if item.image_url and item.image_url.url %}
                                                        <img src="{{ item.image_url.url }}" alt="Phone Image" style="max-height: 140px; max-width: 100%; margin-left: 25px;">
                                                        {% else %}
                                                            <p>No image available</p>
                                                        {% endif %}
                                                    </div>
                                                </a>
                                            </div> 
                                            <div class="col-md-2">
                                                <a href="{% url 'item:add_delete_favorites_compare' item.id %}" type="button" class="btn-close" style="color: #ff9414;"></a>
                                            </div>
                                        </div> 
                    
                                        <a href="{% url 'item:details' item.id %} " style="text-decoration: none; color: inherit; ">
                                            <small>Code: {{ item.id }}</small>
                                            <h6 class="card-title">{{ item.model|format_string|safe }}</h6>
                                            <small>{{ item.comments.count }} comments</small>
                                        </a>
                    
                                        <div class="d-flex justify-content-between mt-2">
                                            <h6>{{ item.price }}$</h6>
                                            <a href='{% url "order:add_to_cart" pk=item.id amount=1 %}' class="shadow-sm btn btn-outline-warning btn-sm" type="button">Add to cart</a>       
                                        </div>
                                    </div>
                                    <div class="list-group-item">
                                        <div>
                                            <small>{{ item.description }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div> 
                </div>
            </div>                      
        </div>
    </div>    
    {% else %}
    <div class="card-body bg-white py-5">
        <div class="container text-center">
            <h5>You haven't added any products to compare.</h5>
            <h6>Do it now!</h6>  
            <a href="{% url 'frontpage' %}" class="btn btn-warning mt-3" type="button">Add items</a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

item/templates/item/details.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% load custom_filters %}

{% block content %}
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'frontpage' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'item:items' %}? query={{ query }}&category={{ item.category_brand.category.id }}">{{ item.category_brand.category }}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'item:items' %}? query={{ query }}&category={{ item.category_brand.category.id }}&brand={{ item.category_brand.brand.id }}">{{ item.category_brand.brand }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ item.model }}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-7">
            <div class="card-body bg-white">
                <div class="container-fluid py-3">
                    <div class="list-group list-group-flush">
                        <div class="list-group-item">
                            <div class="d-inline-flex gap-3">
                                <a href="#review-section" class="h6">Review</a>
                                <a href="#features-section" class="h6">Features</a>
                                <h6>Availability</h6>
                                <a href="#comments-section" class="h6">Comments</a>
                                <h6>Product photo</h6>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="card-body bg-white">
                                <div class="container-fluid">
                                    <div class="text-center">
                                        {% if item.image_url and item.image_url.url %}
                                        <img src="{{ item.image_url.url }}" style="max-width: 300px; max-height: 100%;">
                                        {% else %}
                                            <p>No image available</p>
                                        {% endif %}
                                    </div>
                                    <div class="text-center">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card-body bg-white py-3" style="margin-left: -15px;">
                <div class="container-fluid">
                    <div class="d-flex justify-content-between">
                        <h5 id="review-section">{{ item.model }}</h5>
                        <p>Item code: {{ item.id }}</p>
                    </div>
                    {% if item.availability %}
                        <p>Available</p>
                    {% endif %}

                    {% render_item_stars item %}
                    
                    {% if comments %}
                        <i class="fas fa-comment" style="color: rgb(196, 111, 0);"></i> 
                        <span style="margin-top: -5px;">{{ comments.count }}</span>
                    {% else %}
                        <p>No comments</p>
                    {% endif %}
                    
                    <h4>{{ item.price }}$</h4></br>
                    <div class="container-fluid">
                        <div class="row">
                            {% if item.availability %}
                            <div class="col-md-6">
                                <div class="row">
                                    <a href="{% url 'order:add_to_cart' pk=item.id amount=1 %}" class="btn btn-warning py-2" type="button">Add to cart</a>
                                </div>
                            </div>
                            <div class="col-md-6">
                            {% else %}
                            <div class="col">
                            {% endif %}
                                <div class="row">
                                    <a href="{% url 'conversation:conversation' item_id=item.id %}" class="btn btn-outline-warning py-2" type="button" style="margin-left: 5px;">Message</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body bg-white py-3 mt-2" style="margin-left: -15px;">
                <div class="container-fluid">
                    {% if seller_info %}
                        <a href="{% url 'seller:seller_catalog' seller_info.user.id %}" style="text-decoration: none; color: inherit;">
                            <h5>Seller</h5>                    
                            <div class="d-inline-flex gap-3">
                                {% if seller_info.avatar_url %}
                                    <div class="text-center">
                                        <img src="{{ seller_info.avatar_url.url }}" style="width: 70px; height: 70px;" alt="User Avatar" class="avatar-image">
                                    </div>
                                {% endif %}
                                <div>
                                    <h6>{{ seller_info.user.username }}</h6>
                                    {% if seller_info.phone_number %}
                                        <p>{{ seller_info.phone_number }}</p>
                                    {% else %}
                                        <p>{{ seller_info.user.email }}</p>
                                    {% endif %}
                                </div>                 
                            </div>
                        </a>
                    {% else %}
                        <h6>{{ item.created_by.username }}</h6>
                    {% endif %}  
                </div> 
            </div>
        </div>
    </div>
    
    <h3 id="features-section" class="py-3">Features and description</h3>

    <div class="card-body bg-white py-3">
        <div class="container-fluid">
            {{ item.description }}
        </div>
    </div>

    <h3 id="comments-section" class="py-3">Comments</h3>

    <div class="card-body bg-white">
        <div class="container-fluid py-3">
            <div style="overflow-y: auto; max-height: 400px;">
                <div class="list-group list-group-flush">
                    {% if comments %}
                        {% render_comments comments %}
                    {% else %}
                        No comments yet...
                    {% endif %}
                </div>
            </div>
            <div class="d-flex justify-content-between mt-2">
                <a href="{% url 'item:comments' item.id %}">All comments</a>
                <a href="{% url 'item:comments' item.id %}#comment-form">Leave a comment</a>    
            </div>    
        </div>
    </div>
    {% if related_items %}
        <h3 class="mt-3">Related items</h3>

        <div class="container-fluid mb-5">
            <div class="col-md-12">
                {% render_items related_items request %}
            </div>
        </div>
    {% endif %}
</div>
    
{% endblock %}

item/templates/item/item_stars.html
{% if item.stars %}
    <div class="d-inline-flex gap-1">
        {% for _ in item.stars %}
            <i class="fas fa-star" style="color: rgb(196, 111, 0);"></i>
        {% endfor %}
        {% for _ in item.hollow_stars %}
            <i class="far fa-star" style="color: rgb(196, 111, 0);"></i>
        {% endfor %}
    </div>
{% endif %}